version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: daisy_panel_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/daisy_panel_development
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/daisy_panel_development
    depends_on:
      db:
        condition: service_healthy
    command: ["bundle", "exec", "rails", "solid_queue:start"]

volumes:
  postgres_data:
  bundle_cache:
  node_modules: